title: Hypha Worker Co-operative
email: hello@hypha.coop
phone: +1 437-887-6936
github: https://github.com/hyphacoop
linkedin: https://www.linkedin.com/company/hyphacoop/
twitter: https://twitter.com/hyphacoop/
# facebook: https://www.facebook.com/hyphacoop/
# instagram: https://instagram.com/hyphacoop/

exclude:
# Avoid sending unencrypted private deploy key data.
- scripts/
