title: Hypha Worker Co-operative
email: hello [at] hypha [dot] coop
email-hidden: "%68%65%6c%6c%6f%40%68%79%70%68%61%2e%63%6f%6f%70"
phone: +1 437-887-6936
address: Toronto, ON
github: https://github.com/hyphacoop
linkedin: https://www.linkedin.com/company/hyphacoop/
twitter: https://twitter.com/hyphacoop/
# facebook: https://www.facebook.com/hyphacoop/
# instagram: https://instagram.com/hyphacoop/

exclude:
# Avoid sending unencrypted private deploy key data.
- scripts/
# For building on TravisCI.
# See: https://jekyllrb.com/docs/continuous-integration/travis-ci/
- vendor/bundle
